PLATFORM ?= linux

CP = /bin/cp
MKDIR = /bin/mkdir -p
MV = /bin/mv
RM = /bin/rm -rf

NTHREAD_DIR = $(CURDIR)
NTHREAD_SOURCE_DIR = $(NTHREAD_DIR)/src
NTHREAD_SOURCES = $(wildcard $(NTHREAD_SOURCE_DIR)/*.c)
NTHREAD_INCLUDE_DIR = $(NTHREAD_DIR)/include

NEPTUNE_DIR = $(NTHREAD_DIR)/neptune
NEPTUNE_SOURCE_DIR = $(NEPTUNE_DIR)/src
NEPTUNE_SOURCES = $(wildcard $(NEPTUNE_SOURCE_DIR)/*.c)
NEPTUNE_INCLUDE_DIR = $(NEPTUNE_DIR)/include

CC = /bin/cc
CFLAGS = -Wall -g -I$(NEPTUNE_INCLUDE_DIR) -I$(NTHREAD_INCLUDE_DIR) -static

ifeq ($(PLATFORM), linux)
	BUILD_DIR = $(CURDIR)/build
else
	BUILD_DIR = $(CURDIR)/build/$(PLATFORM)
endif

TESTS_DIR = $(CURDIR)/tests
TESTS_BUILD_DIR = $(BUILD_DIR)/tests

INJECT_T_TARGET = inject
INJECT_T_BUILD_DIR = $(TESTS_BUILD_DIR)/$(INJECT_T_TARGET).dir
INJECT_T_CFLAGS = -DLOG_LEVEL_3 -DNTJAVA_DISABLE=1

INJECT_T_SOURCE = $(TESTS_DIR)/$(INJECT_T_TARGET).c
INJECT_T_OBJECT_DIR = $(INJECT_T_BUILD_DIR)/obj
INJECT_T_OBJECT = $(INJECT_T_OBJECT_DIR)/$(INJECT_T_TARGET).o

INJECT_T_SOURCES = $(NEPTUNE_SOURCES) $(NTHREAD_SOURCES) $(INJECT_T_SOURCE)
INJECT_T_OBJECTS = $(patsubst $(NEPTUNE_SOURCE_DIR)/%.c,$(INJECT_T_OBJECT_DIR)/%.o, $(NEPTUNE_SOURCES)) $(patsubst $(NTHREAD_SOURCE_DIR)/%.c,$(INJECT_T_OBJECT_DIR)/%.o, $(NTHREAD_SOURCES)) $(INJECT_T_OBJECT)


JAVAINJECT_T_TARGET = javainject
JAVAINJECT_T_BUILD_DIR = $(TESTS_BUILD_DIR)/$(JAVAINJECT_T_TARGET).dir
JAVAINJECT_T_CFLAGS = -DLOG_LEVEL_3

JAVAINJECT_T_SOURCE = $(TESTS_DIR)/$(JAVAINJECT_T_TARGET).c
JAVAINJECT_T_OBJECT_DIR = $(JAVAINJECT_T_BUILD_DIR)/obj
JAVAINJECT_T_OBJECT = $(JAVAINJECT_T_OBJECT_DIR)/$(JAVAINJECT_T_TARGET).o

JAVAINJECT_T_SOURCES = $(NEPTUNE_SOURCES) $(NTHREAD_SOURCES) $(JAVAINJECT_T_SOURCE)
JAVAINJECT_T_OBJECTS = $(patsubst $(NEPTUNE_SOURCE_DIR)/%.c,$(JAVAINJECT_T_OBJECT_DIR)/%.o, $(NEPTUNE_SOURCES)) $(patsubst $(NTHREAD_SOURCE_DIR)/%.c,$(JAVAINJECT_T_OBJECT_DIR)/%.o, $(NTHREAD_SOURCES)) $(JAVAINJECT_T_OBJECT)

CREATE_DIRS = $(BUILD_DIR) $(INJECT_T_BUILD_DIR) $(INJECT_T_OBJECT_DIR) $(JAVAINJECT_T_BUILD_DIR) $(JAVAINJECT_T_OBJECT_DIR)

ifeq ($(PLATFORM), windows)
	TARGETS = $(INJECT_T_TARGET) $(JAVAINJECT_T_TARGET)
else ifeq ($(PLATFORM), linux)
	TARGETS = $(INJECT_T_TARGET)
else
	TARGETS = $(INJECT_T_TARGET)
endif

default: create_dirs all

all: $(TARGETS)


$(INJECT_T_TARGET): $(INJECT_T_OBJECTS)
	$(CC) $(CFLAGS) -o $(TESTS_BUILD_DIR)/$(INJECT_T_TARGET) $^
	strip $(TESTS_BUILD_DIR)/$(INJECT_T_TARGET).exe

$(INJECT_T_OBJECT_DIR)/%.o: $(NEPTUNE_SOURCE_DIR)/%.c
	$(CC) $(CFLAGS) $(INJECT_T_CFLAGS) -c $< -o $@

$(INJECT_T_OBJECT_DIR)/%.o: $(NTHREAD_SOURCE_DIR)/%.c
	$(CC) $(CFLAGS) $(INJECT_T_CFLAGS) -c $< -o $@

$(INJECT_T_OBJECT): $(INJECT_T_SOURCE)
	$(CC) $(CFLAGS) $(INJECT_T_CFLAGS) -c $< -o $@


$(JAVAINJECT_T_TARGET): $(JAVAINJECT_T_OBJECTS)
	$(CC) $(CFLAGS) -o $(TESTS_BUILD_DIR)/$(JAVAINJECT_T_TARGET) $^
	strip $(TESTS_BUILD_DIR)/$(JAVAINJECT_T_TARGET).exe

$(JAVAINJECT_T_OBJECT_DIR)/%.o: $(NEPTUNE_SOURCE_DIR)/%.c
	$(CC) $(CFLAGS) $(JAVAINJECT_T_CFLAGS) -c $< -o $@

$(JAVAINJECT_T_OBJECT_DIR)/%.o: $(NTHREAD_SOURCE_DIR)/%.c
	$(CC) $(CFLAGS) $(JAVAINJECT_T_CFLAGS) -c $< -o $@

$(JAVAINJECT_T_OBJECT): $(JAVAINJECT_T_SOURCE)
	$(CC) $(CFLAGS) $(JAVAINJECT_T_CFLAGS) -c $< -o $@


create_dirs:
	$(MKDIR) $(CREATE_DIRS)

clean:
	$(RM) $(CREATE_DIRS)
